# Generated by Django 4.2.5 on 2023-10-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
    ]
