# Generated by Django 4.2.5 on 2023-10-15 19:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.ImageField(upload_to='', validators=[django.core.validators.MinLengthValidator(0, 'Avaliação não pode ser inferior a 0'), django.core.validators.MaxLengthValidator(5, 'Avaliação não pode ser superior a 5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='movies.movie')),
            ],
        ),
    ]
